### PR TITLE
Added pod stats for issue #4

### PR DESCRIPTION
**Pull request by am831**
- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

Link to the issue: https://github.com/MLH-Fellowship/prep-portfolio-23.APR.PREP.2/issues/4

### CODE REVIEW

**Review by grace-omotoso — CHANGES_REQUESTED** [review]
These stats should not be hard coded. Please, leverage GitHub API to pull the stats. Contributions based on PRs will show a lot of people who have 0 PRs as though they have not made any contributions. Let us base contributions on a number of commits. We can leave this open for discussion tomorrow. Also, improve the table formatting, see attached sample

leaderboard

Here is a link to GitHub API documentation - https://docs.github.com/en/rest/metrics/statistics?apiVersion=2022-11-28

**Comment by grace-omotoso** [comment]
Mukhammad will collaborate with Alisha on this

**Comment by grace-omotoso** [comment]
@am831 Great job, please, fix merge conflicts. Thanks

**Review by grace-omotoso — CHANGES_REQUESTED** [review]
Sorry, this was not caught before. Please, remove gem file from commit

**Comment by am831** [comment]
I deleted gemfile but I'm not sure why the checks failed.

**Review by grace-omotoso — COMMENTED** [review]
This PR is distorting the way the project cards are displayed. Please, check you styling and test properly. I also see a toggle button. Are you also working on the toggle issue in this PR? As a best practice, a PR should be used to solve an issue.
This is how the project cards look on my end.
project_cards

**Review by grace-omotoso — CHANGES_REQUESTED** [review]
Please, remove changes to Gemfile from commit.

**Comment by am831** [comment]
I removed all the code from the toggle issue and removed gemfile. Should be good now thanks.

**Comment by grace-omotoso** [comment]
@am831 please, fix merge conflicts and remove gem file changes from commit

**Comment by grace-omotoso** [comment]
@am831 I fixed the merge conflicts but the preview looks distorted. Please, look into this.

**Comment by am831** [comment]
@grace-omotoso I believe I fixed the distortion, I also changed the cards to two columns instead of 3, because the 3rd was cut off on my end. Let me know if you want me to change the height of the banner, the title is displayed over our profile pictures, but I'm not sure if that is an issue.

**Comment by grace-omotoso** [comment]
Great effort @am831.

**Pull request merged**
