### PR TITLE
Issue #9 and #13 done

### PR DESCRIPTION
**Pull request by hrl-2024**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by hrl-2024** [comment]
Code now reflect changes from upstream (show MLH Prep instead of MLH Fellow)

**Comment by hrl-2024** [comment]
Explicit back buttons in the page banner added

**Review by grace-omotoso — CHANGES_REQUESTED** [review]
Please, remove the gemlock file from your commit. I don't want to delay this PR, if this is something that won't take less time, use a button instead of an arrow for the Back functionality. This button should be below the page with a blue background that matches the nav bar and a white text. Don't worry about it if it will take some time to fix but take out the back arrow.

**Comment by hrl-2024** [comment]
Gemfile.Lock file removed as requested (if merged, main branch Gemfile.Lock might also be deleted. Gemfile.Lock file specified Jekyll dependency which is required to run the site.)

Back button and background extended as needed.

**Review by grace-omotoso — APPROVED** [review]
Looks good to me.

**Pull request merged**
