### PR TITLE
Redo navbar and navlinks; make a backtotop btn. Issue #8 

### PR DESCRIPTION
**Pull request by MadaniKK**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

Issue 8 #8

### CODE REVIEW

**Review by grace-omotoso — COMMENTED** [review]
remove commented code

**Comment by grace-omotoso** [comment]
@MadaniKK there are several commented code in the commit, please remove and update your PR. Thanks

**Review by grace-omotoso — COMMENTED** [review]
remove commented code

**Comment by MadaniKK** [comment]
> remove commented code

Sorry for the late reply, I just got access to my laptop, commented code a removed now.

**Review by grace-omotoso — APPROVED** [review]
Looks good to me.

**Pull request merged**
