### PR TITLE
fixes issues/12 with dynamic picture layout

### PR DESCRIPTION
**Pull request by cyu60**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

Resolved Issue 12 https://github.com/MLH-Fellowship/prep-portfolio-23.APR.PREP.2/issues/12

### CODE REVIEW

**Review by grace-omotoso — COMMENTED** [review]
improve_picture layout

It looks too big on my big screen. See attached.

**Comment by mukhsadr** [comment]
Thanks for your contribution! Following a clear and consistent format for pull request titles is important for making it easier to understand the changes being made. In this case, I suggest changing the title to something like 'fix: dynamically adjust picture layout to address issue #12'. Keep up the great work!

**Comment by grace-omotoso** [comment]
Riley/Julia will collaborate with Chinat to get this fixed

**Comment by cyu60** [comment]
@grace-omotoso I think that I patched the issue. Please kindly review to see if the issue still exists

**Review by grace-omotoso — APPROVED** [review]

**Pull request merged**
