### PR TITLE
Dark theme toggle for issue #14

### PR DESCRIPTION
**Pull request by am831**
- [x ] My Pod Leader knows I'm working on this Pull Request
- [x ] I've explained what the Pull Request is adding.
- [x ] I've explained why this is important.

Close issue #14

### CODE REVIEW

**Review by grace-omotoso — CHANGES_REQUESTED** [review]
Remove gemlock changes from commit. Also, project cards are distorted. Please, check your styling.

**Comment by mukhsadr** [comment]
@grace-omotoso I fixed the bugs you mentioned in the comment.

**Comment by grace-omotoso** [comment]
@am831 Please, fix merge conflicts and remove gem file changes from commit

**Comment by grace-omotoso** [comment]
@mukhsadr preview looks distorted. Please, fix merge conflicts.

**Comment by am831** [comment]
@grace-omotoso this pr also contains the pod stats code, so you can merge this pr instead of our other one.

**Pull request merged**
